export const coffees = [
  {
    id: 1,
    name: "Espresso",
    category: "Classiques",
    image: "/images/hero1.png",
    available: true,
    description: "Un café intense et corsé, parfait pour les amateurs de saveurs pures.",
    ingredients: ["Espresso", "Eau"],
    sizes: [
      { key: "S", label: "S", price: 4 },
      { key: "M", label: "M", price: 5 },
    ],
  },
  {
    id: 2,
    name: "Cappuccino",
    category: "Lattés",
    image: "/images/hero1.png",
    available: false,
    description: "Un cappuccino onctueux avec une mousse légère et un goût équilibré.",
    ingredients: ["Espresso", "Lait", "Mousse de lait"],
    sizes: [
      { key: "S", label: "S", price: 6 },
      { key: "M", label: "M", price: 7.5 },
      { key: "L", label: "L", price: 9 },
    ],
  },
  {
    id: 3,
    name: "Iced Latte",
    category: "Glacés",
    image: "/images/hero1.png",
    available: true,
    description: "Une boisson rafraîchissante à base d’espresso, de lait et de glaçons.",
    ingredients: ["Espresso", "Lait", "Glaçons"],
    sizes: [
      { key: "M", label: "M", price: 8 },
      { key: "L", label: "L", price: 10 },
    ],
  },
  {
    id: 4,
    name: "Americano",
    category: "Classiques",
    image: "/images/hero1.png",
    available: true,
    description: "Un café allongé aux arômes subtils, léger et agréable à déguster.",
    ingredients: ["Espresso", "Eau chaude"],
    sizes: [
      { key: "S", label: "S", price: 4.5 },
      { key: "M", label: "M", price: 5.5 },
    ],
  },
  {
    id: 5,
    name: "Ristretto",
    category: "Classiques",
    image: "/images/hero1.png",
    available: false,
    description: "Une version plus courte et plus intense de l’espresso, au goût puissant.",
    ingredients: ["Espresso concentré"],
    sizes: [
      { key: "S", label: "S", price: 4 },
      { key: "M", label: "M", price: 5 },
    ],
  },
  {
    id: 6,
    name: "Flat White",
    category: "Lattés",
    image: "/images/hero1.png",
    available: true,
    description: "Un café doux et crémeux avec une texture soyeuse et équilibrée.",
    ingredients: ["Espresso", "Lait micro-moussé"],
    sizes: [
      { key: "S", label: "S", price: 6 },
      { key: "M", label: "M", price: 7 },
      { key: "L", label: "L", price: 8.5 },
    ],
  },
  {
    id: 7,
    name: "Café Latte",
    category: "Lattés",
    image: "/images/hero1.png",
    available: true,
    description: "Un latte doux et réconfortant, idéal pour une pause gourmande.",
    ingredients: ["Espresso", "Lait", "Mousse légère"],
    sizes: [
      { key: "S", label: "S", price: 6 },
      { key: "M", label: "M", price: 7.5 },
      { key: "L", label: "L", price: 9 },
    ],
  },
  {
    id: 8,
    name: "Iced Americano",
    category: "Glacés",
    image: "/images/hero1.png",
    available: true,
    description: "Une boisson fraîche et légère avec toute l’intensité du café.",
    ingredients: ["Espresso", "Eau", "Glaçons"],
    sizes: [
      { key: "M", label: "M", price: 7 },
      { key: "L", label: "L", price: 8.5 },
    ],
  },
  {
    id: 9,
    name: "Cold Brew",
    category: "Glacés",
    image: "/images/hero1.png",
    available: true,
    description: "Un café infusé à froid, doux, rafraîchissant et moins acide.",
    ingredients: ["Café infusé à froid", "Eau", "Glaçons"],
    sizes: [
      { key: "M", label: "M", price: 8 },
      { key: "L", label: "L", price: 9.5 },
    ],
  },
  {
    id: 10,
    name: "Frappé",
    category: "Glacés",
    image: "/images/hero1.png",
    available: false,
    description: "Une boisson glacée mousseuse et rafraîchissante, parfaite pour l’été.",
    ingredients: ["Café", "Lait", "Glace", "Sucre"],
    sizes: [
      { key: "M", label: "M", price: 8 },
      { key: "L", label: "L", price: 10 },
    ],
  },
  {
    id: 11,
    name: "Café Mocha",
    category: "Moka & Chocolat",
    image: "/images/hero1.png",
    available: true,
    description: "Un mélange gourmand d’espresso, de lait et de chocolat.",
    ingredients: ["Espresso", "Lait", "Chocolat"],
    sizes: [
      { key: "S", label: "S", price: 7 },
      { key: "M", label: "M", price: 8.5 },
      { key: "L", label: "L", price: 10 },
    ],
  },
  {
    id: 12,
    name: "White Mocha",
    category: "Moka & Chocolat",
    image: "/images/hero1.png",
    available: true,
    description: "Une version douce et crémeuse du mocha avec une touche sucrée.",
    ingredients: ["Espresso", "Lait", "Chocolat blanc"],
    sizes: [
      { key: "S", label: "S", price: 7.5 },
      { key: "M", label: "M", price: 9 },
    ],
  },
  {
    id: 13,
    name: "Choco Latte",
    category: "Moka & Chocolat",
    image: "/images/hero1.png",
    available: true,
    description: "Un latte gourmand relevé par de délicieuses notes chocolatées.",
    ingredients: ["Espresso", "Lait", "Chocolat"],
    sizes: [
      { key: "S", label: "S", price: 7 },
      { key: "M", label: "M", price: 8 },
      { key: "L", label: "L", price: 9.5 },
    ],
  },
  {
    id: 14,
    name: "Vanilla Latte",
    category: "Aromatisés",
    image: "/images/hero1.png",
    available: true,
    isNew: true,
    description: "Un latte doux et parfumé à la vanille pour une pause délicatement sucrée.",
    ingredients: ["Espresso", "Lait", "Vanille"],
    sizes: [
      { key: "S", label: "S", price: 7 },
      { key: "M", label: "M", price: 8.5 },
    ],
  },
  {
    id: 15,
    name: "Caramel Latte",
    category: "Aromatisés",
    image: "/images/hero1.png",
    available: true,
    isNew: true,
    description: "Une boisson onctueuse et gourmande avec de savoureuses notes de caramel.",
    ingredients: ["Espresso", "Lait", "Caramel"],
    sizes: [
      { key: "S", label: "S", price: 7 },
      { key: "M", label: "M", price: 8.5 },
      { key: "L", label: "L", price: 10 },
    ],
  },
  {
    id: 16,
    name: "Hazelnut Latte",
    category: "Aromatisés",
    image: "/images/hero1.png",
    available: true,
    isNew: true,
    description: "Un latte parfumé à la noisette, à la fois doux, riche et réconfortant.",
    ingredients: ["Espresso", "Lait", "Noisette"],
    sizes: [
      { key: "S", label: "S", price: 7 },
      { key: "M", label: "M", price: 8 },
    ],
  },
  {
    id: 17,
    name: "Coconut Latte",
    category: "Aromatisés",
    image: "/images/hero1.png",
    available: false,
    description: "Un latte original aux notes exotiques et légèrement sucrées de coco.",
    ingredients: ["Espresso", "Lait", "Noix de coco"],
    sizes: [
      { key: "M", label: "M", price: 8.5 },
      { key: "L", label: "L", price: 10 },
    ],
  },
  {
    id: 18,
    name: "Signature House",
    category: "Signatures",
    image: "/images/hero1.png",
    available: true,
    description: "La création signature de Coffee House, riche, élégante et généreuse.",
    ingredients: ["Espresso", "Lait", "Sirop signature"],
    sizes: [
      { key: "S", label: "S", price: 9 },
      { key: "M", label: "M", price: 10.5 },
    ],
  },
  {
    id: 19,
    name: "Caramel Dream",
    category: "Signatures",
    image: "/images/hero1.png",
    available: true,
    description: "Une recette signature gourmande mêlant douceur lactée et caramel fondant.",
    ingredients: ["Espresso", "Lait", "Caramel", "Crème légère"],
    sizes: [
      { key: "M", label: "M", price: 10 },
      { key: "L", label: "L", price: 12 },
    ],
  },
  {
    id: 20,
    name: "Royal Latte",
    category: "Signatures",
    image: "/images/hero1.png",
    available: true,
    isNew: true,
    description: "Un latte raffiné aux saveurs généreuses pour une expérience premium.",
    ingredients: ["Espresso", "Lait", "Vanille", "Crème légère"],
    sizes: [
      { key: "M", label: "M", price: 10 },
      { key: "L", label: "L", price: 12 },
    ],
  },
  {
    id: 21,
    name: "Decaf Espresso",
    category: "Décaféiné",
    image: "/images/hero1.png",
    available: false,
    description: "Toute l’intensité d’un espresso, sans caféine.",
    ingredients: ["Espresso décaféiné"],
    sizes: [
      { key: "S", label: "S", price: 4.5 },
      { key: "M", label: "M", price: 5.5 },
    ],
  },
  {
    id: 22,
    name: "Decaf Latte",
    category: "Décaféiné",
    image: "/images/hero1.png",
    available: true,
    description: "Un latte doux et crémeux, idéal pour savourer sans caféine.",
    ingredients: ["Espresso décaféiné", "Lait"],
    sizes: [
      { key: "S", label: "S", price: 6 },
      { key: "M", label: "M", price: 7.5 },
    ],
  },
  {
    id: 23,
    name: "Decaf Cappuccino",
    category: "Décaféiné",
    image: "/images/hero1.png",
    available: true,
    description: "Un cappuccino léger et mousseux, en version décaféinée.",
    ingredients: ["Espresso décaféiné", "Lait", "Mousse de lait"],
    sizes: [
      { key: "S", label: "S", price: 6 },
      { key: "M", label: "M", price: 7 },
    ],
  },
];


